### ISSUE TITLE
Awesome 3.5 and Lua 5.1 on Gentoo: awful.spawn returns 'nil'

### ISSUE THREAD

**Issue by b33rcity** [stefano-m/awesome-power_widget#1]
I have just succeeded in installing this widget to my laptop, but I encountered some trouble that took a little while to work around. 

The environment:

Gentoo, awesome 3.5.9, Lua 5.1.5, using xfce-power-manager for gui client.

After using luarocks to install power_widget and putting the necessary code into rc.lua, I got the error `attempt to index spawn (a nil value field)` pointing at line 27:

`local spawn_with_shell = awful.spawn.with_shell or awful.util.spawn_with_shell`

I was able to work around this error by adding the following lines:

`package.path = package.path .. ';/usr/share/awesome/lib/awful/?.lua'`
`local util = require("util")`

and changing line 27 (now line 29) to `local spawn_with_shell = util.spawn_with_shell`

I hope it's useful to somebody :)

**Comment by stefano-m** [comment]
Hello! Happy to know that you solved the issue.

Lately I have been using Awesome 4.x with Lua 5.2 and 5.3.

I think this can be solved by updating the documentation.

Could you try the following for me please?

1. Revert the changes in the widget file
2. add `require("awful.util")` to the top of your `rc.lua`
3. see if that works

If that's the case, I can update the `README`.

**Comment by b33rcity** [comment]
That brings back the error, sadly. I also tried using `local awful.util = require("awful.util")` to no effect. 

Full stacktrace:
```
error while running function
stack traceback:
    /usr/lib64/luarocks/lua/5.1/power_widget.lua:27: in main chunk 
    [C]: in function 'require'
    /root/.config/awesome/rc.lua:45: in main chunk
error: /usr/lib64/lua/luarocks/share/lua/5.1/power_widget.lua:27: attempt to index field 'spawn' (a nil value)
```

**Comment by stefano-m** [comment]
Thanks for trying.

It may be that in Awesome 3.5 one has to require `awful.util` explicitly?

I'll try to see if one can `require` `awful.util` conditionally so you can check whether it works.

**Comment by stefano-m** [comment]
Well,

at least in Awesome 4.x the following works:

```lua
awful = require('awful')
awful.util.spawn_with_shell ~= nil -- true
awful.spawn.with_shell ~= nil -- true
```

So I am a bit surprised that it is not the case in Awesome 3.5 that `awful.util` is not recognized. Maybe it's an issue with Gentoo (I don't use that distro)? You can check what your `package.path` contains.

Maybe you could try to monkey-patch your `rc.lua` directly? Something like:

```lua
package.path = package.path .. ';/usr/share/awesome/lib/awful/?.lua'
require('awful.util')
```

**Comment by b33rcity** [comment]
That was also something I tried with similar results. Tbh, with awesome and Lua having moved on from these versions already (which I didn't know before I installed them in Gentoo), I think it would be fair to mark this as WONTFIX and just leave a note about the workaround to cover any other noobies like me coming along while the Gentoo folks finish testing awesome 4.

**Comment by stefano-m** [comment]
I agree with you. Closing.
